### ISSUE TITLE
bug new booking

### ISSUE THREAD

**Issue by AD11FL** [An3eljo/CinemaBookingSystem#2]
CinemaBookingSystem/CinemaBookingSystem/View/MainWindow.xaml.cs

`private void LabelNewBooking_OnMouseLeftButtonUp(object sender, MouseButtonEventArgs e)
 {
    FrameDisplayContent.Source = new Uri ("Customer/CreateCustomer.xaml", UriKind.Relative);
 }`

**Comment by An3eljo** [comment]
[https://github.com/An3eljo/CinemaBookingSystem/commit/f703d71ac1fd3fa8a3b88f082a540feb7a892214](solving commit)
